version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000" # Ajusta si usas otro puerto expuesto
    restart: always

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    ports:
      - "5002:5002"
    volumes:
      - ./delivery-service:/src
    command: npm start
    restart: always

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "5001:5001"
    volumes:
      - ./inventory-service:/src
    command: npm start
    restart: always

volumes:
  redis-data:
